// SPDX-License-Identifier: GPL-2.0
#include "bpf_loader.h"
#include "config.h"

#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include <net/if.h>
#include <linux/if_link.h>   // XDP_FLAGS_*
#include <cstdio>
#include <cstring>
#include <unistd.h>

// Generated by `bpftool gen skeleton` (see top-level Makefile).
#include "xdp_monitor.skel.h"

namespace netmon {

static int libbpf_print(enum libbpf_print_level level, const char* fmt, va_list args) {
    if (level == LIBBPF_DEBUG) return 0;
    return vfprintf(stderr, fmt, args);
}

BpfLoader::BpfLoader(const Config& cfg) : cfg_(cfg) {
    libbpf_set_print(libbpf_print);
}

BpfLoader::~BpfLoader() {
    detach();
    if (rb_) ring_buffer__free(rb_);
    if (skel_) xdp_monitor_bpf__destroy(skel_);
}

static __u32 xdp_flags_for(const std::string& mode) {
    if (mode == "native") return XDP_FLAGS_DRV_MODE;
    if (mode == "hw")     return XDP_FLAGS_HW_MODE;
    return XDP_FLAGS_SKB_MODE;   // generic — works on tap/veth/bridge
}

bool BpfLoader::load_and_attach() {
    skel_ = xdp_monitor_bpf__open();
    if (!skel_) {
        std::fprintf(stderr, "failed to open BPF skeleton\n");
        return false;
    }
    if (xdp_monitor_bpf__load(skel_)) {
        std::fprintf(stderr, "failed to load BPF object (need root / CAP_BPF)\n");
        return false;
    }

    int prog_fd = bpf_program__fd(skel_->progs.xdp_monitor);
    __u32 flags = xdp_flags_for(cfg_.xdp_mode);

    for (const auto& name : cfg_.interfaces) {
        unsigned int idx = if_nametoindex(name.c_str());
        if (idx == 0) {
            std::fprintf(stderr, "interface '%s' not found, skipping\n", name.c_str());
            continue;
        }
        // Use the libbpf XDP attach API with explicit flags.
        LIBBPF_OPTS(bpf_xdp_attach_opts, opts);
        int err = bpf_xdp_attach(idx, prog_fd, flags, &opts);
        if (err) {
            std::fprintf(stderr,
                "failed to attach XDP to %s (idx %u) in %s mode: %s\n",
                name.c_str(), idx, cfg_.xdp_mode.c_str(), std::strerror(-err));
            // Fall back to generic mode if a native attach failed.
            if (flags != XDP_FLAGS_SKB_MODE) {
                err = bpf_xdp_attach(idx, prog_fd, XDP_FLAGS_SKB_MODE, &opts);
                if (!err)
                    std::fprintf(stderr, "  -> attached %s in skb (generic) mode\n",
                                 name.c_str());
            }
        }
        if (!err) {
            attached_.push_back({(int)idx, name});
            std::fprintf(stderr, "attached XDP to %s (ifindex %u)\n",
                         name.c_str(), idx);
        }
    }
    return !attached_.empty();
}

void BpfLoader::detach() {
    __u32 flags = xdp_flags_for(cfg_.xdp_mode);
    for (const auto& a : attached_) {
        bpf_xdp_detach(a.ifindex, flags, nullptr);
        // Best-effort generic detach too.
        bpf_xdp_detach(a.ifindex, XDP_FLAGS_SKB_MODE, nullptr);
    }
    attached_.clear();
}

std::vector<FlowEntry> BpfLoader::scrape_flows() {
    std::vector<FlowEntry> out;
    int fd = bpf_map__fd(skel_->maps.flow_map);

    flow_key key{}, next{};
    bool have_key = false;
    // Iterate using get_next_key starting from a zeroed/NULL key.
    while (bpf_map_get_next_key(fd, have_key ? &key : nullptr, &next) == 0) {
        FlowEntry e;
        e.key = next;
        if (bpf_map_lookup_elem(fd, &next, &e.stats) == 0)
            out.push_back(e);
        key = next;
        have_key = true;
    }
    return out;
}

void BpfLoader::delete_flows(const std::vector<flow_key>& keys) {
    int fd = bpf_map__fd(skel_->maps.flow_map);
    for (const auto& k : keys)
        bpf_map_delete_elem(fd, &k);
}

void BpfLoader::read_global_stats(uint64_t out[__STAT_MAX]) {
    int fd = bpf_map__fd(skel_->maps.global_stats);
    int ncpu = libbpf_num_possible_cpus();
    if (ncpu < 1) ncpu = 1;
    std::vector<uint64_t> percpu(ncpu);
    for (uint32_t slot = 0; slot < __STAT_MAX; ++slot) {
        out[slot] = 0;
        if (bpf_map_lookup_elem(fd, &slot, percpu.data()) == 0) {
            for (int c = 0; c < ncpu; ++c) out[slot] += percpu[c];
        }
    }
}

std::vector<BpfLoader::IfCounters> BpfLoader::read_if_stats() {
    std::vector<IfCounters> out;
    int fd = bpf_map__fd(skel_->maps.if_stats_map);
    __u32 key = 0, next = 0;
    bool have = false;
    while (bpf_map_get_next_key(fd, have ? &key : nullptr, &next) == 0) {
        IfCounters c{};
        c.ifindex = next;
        if (bpf_map_lookup_elem(fd, &next, &c.st) == 0) {
            char name[IF_NAMESIZE] = {0};
            if (if_indextoname(next, name)) c.name = name;
            out.push_back(c);
        }
        key = next; have = true;
    }
    return out;
}

bool BpfLoader::blocklist_add(uint32_t ipv4_be) {
    int fd = bpf_map__fd(skel_->maps.blocklist_map);
    uint8_t one = 1;
    return bpf_map_update_elem(fd, &ipv4_be, &one, BPF_ANY) == 0;
}

bool BpfLoader::blocklist_del(uint32_t ipv4_be) {
    int fd = bpf_map__fd(skel_->maps.blocklist_map);
    return bpf_map_delete_elem(fd, &ipv4_be) == 0;
}

int BpfLoader::l7_trampoline(void* ctx, void* data, size_t len) {
    auto* self = static_cast<BpfLoader*>(ctx);
    if (len >= sizeof(l7_event) && self->l7_cb_)
        self->l7_cb_(static_cast<const l7_event*>(data));
    return 0;
}

bool BpfLoader::open_l7_ringbuf(L7Callback cb) {
    l7_cb_ = std::move(cb);
    int fd = bpf_map__fd(skel_->maps.l7_events);
    rb_ = ring_buffer__new(fd, &BpfLoader::l7_trampoline, this, nullptr);
    return rb_ != nullptr;
}

int BpfLoader::poll_l7(int timeout_ms) {
    if (!rb_) return -1;
    return ring_buffer__poll(rb_, timeout_ms);
}

} // namespace netmon
